---
title: "Scatter plots"
author: "Stef Meliss"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

rm(list = ls())


# theme
# ambition colours 2023 #
navy = "#474C68"
white = "#FFFFFF"
black = "#000000"
cyan = "#14B4E9"
coral = "#E94B58"
yellow = "#FFCC00"
green = "#C1D10F"
teal = "#00987C"
blue = "#006FB7"
purple = "#6D2160"
orange = "#EC642D"
red = "#BF1C1D"

# combine to palette
ambition_palette_bright <- c(cyan, coral, teal, purple, orange) # bright palette
ambition_palette_accent <- c(yellow, blue, red)
ambition_palette <- c(ambition_palette_bright, ambition_palette_accent) # 8 colours without ITT green
col_on_white <- c(red, blue, purple, navy) # colours that can be used for all text sizes if background is white
col_on_white_heeadings <- c(coral, teal, orange) # colours that can only be used for headings if background is white

# declare dominant and non-dominant colour in plots
dominant_col <- coral
nondominant_col <- navy

# load libraries
library(ggplot2)
library(extrafont)
# if not run before, run
# font_import()

# define theme for plot
theme <- theme_bw() + theme(
  text=element_text(family="Segoe UI"),
  plot.title = element_text(size=14, face="bold"),
  axis.title = element_text(size=10, face="bold"),
  legend.title = element_blank(),
  legend.position = "bottom"
)


# download helper functions
devtools::source_url("https://github.com/stefaniemeliss/MAGMOT/blob/master/functions/errorbars.R?raw=TRUE")



```

```{r, include=F}
set.seed(20052024) # date of meeting

n = 100

# simulate data
dat <- faux::rnorm_multi(n = n, 
                         mu = c(6, 6, 7, 10),
                         sd = c(1, 1, 1, 1),
                         r = c(0, 0.3, 0, 0, .7, 0), 
                         varnames = c("t1_g1", "t1_g2", "t2_g1", "t2_g2"),
                         empirical = FALSE)

# format data: wide data
df <- data.frame(id = 1:n,
                 group = c(rep("cont", n), rep("exp", n)),
                 t1 = c(dat$t1_g1, dat$t1_g2),
                 t2 = c(dat$t2_g1, dat$t2_g2))
# format data: long data
df_long <- reshape2::melt(df, id.vars = c("id", "group"), variable.name = "timepoint")

```

## Scatterplots

```{r, echo = F}

# scatter plot
plt_all <- ggplot(data = df, aes(x = t1, y = t2)) +
  geom_point(color = nondominant_col, shape = 20) +
  #facet_wrap(. ~ group, nrow = 2) + 
  stat_smooth(formula = y ~ x, method = "lm", fullrange = T, se = T, alpha=0.1, fill = "black", color = dominant_col) +
  theme + 
  #'scale_x_continuous(breaks=seq(0, 10, 2)) +
  xlab("Baseline assessment") + ylab("Outcome assessment") +
  ggpubr::stat_cor(method = "pearson", cor.coef.name = "r",
                   p.accuracy = 0.001, r.accuracy = 0.01)
plt_all


# grouped scatterplot with 
plt_grp <- ggplot(data = df, aes(x = t1, y = t2)) +
  geom_point(color = nondominant_col, shape = 20) +
  facet_wrap(. ~ group, nrow = 2) + 
  stat_smooth(formula = y ~ x, method = "lm", fullrange = T, se = T, alpha=0.1, fill = "black", color = dominant_col) +
  theme + 
  xlab("Baseline assessment") + ylab("Outcome assessment") +
  ggpubr::stat_cor(method = "pearson", cor.coef.name = "r",
                   p.accuracy = .001, r.accuracy = .01)
plt_grp

```



```{r, echo = F}

# scatter plot
plt_all <- ggplot(data = df, aes(x = t1, y = t2)) +
  geom_point(shape = 20) +
  #facet_wrap(. ~ group, nrow = 2) + 
  stat_smooth(formula = y ~ x, method = "lm", fullrange = T, se = T, alpha=0.1, col = navy, fill = "black") +
  theme + 
  #'scale_x_continuous(breaks=seq(0, 10, 2)) +
  xlab("Baseline assessment") + ylab("Outcome assessment") +
  ggpubr::stat_cor(method = "pearson", cor.coef.name = "r",
                   p.accuracy = 0.001, r.accuracy = 0.01)
plt_all


# grouped scatterplot 
plt_grp <- ggplot(data = df, aes(x = t1, y = t2, col = group)) +
  geom_point(shape = 20)+
  facet_wrap(. ~ group, nrow = 2) + 
  stat_smooth(formula = y ~ x, method = "lm", fullrange = T, se = T, alpha=0.1, fill = "black") +
  scale_color_manual(values = c(blue, red)) +
  theme + 
  theme(legend.position = "none") +
  xlab("Baseline assessment") + ylab("Outcome assessment") +
  ggpubr::stat_cor(method = "pearson", cor.coef.name = "r",
                   p.accuracy = .001, r.accuracy = .01)
plt_grp


# grouped scatterplot 
plt_grp <- ggplot(data = df, aes(x = t1, y = t2, col = group)) +
  geom_point(shape = 20)+
  facet_wrap(. ~ group, nrow = 2) + 
  stat_smooth(formula = y ~ x, method = "lm", fullrange = T, se = T, alpha=0.1, fill = "black") +
  scale_color_manual(values = c(blue, red)) +
  theme + 
  theme(legend.position = "none") +
  xlab("Baseline assessment") + ylab("Outcome assessment") +
  ggpubr::stat_cor(method = "pearson", cor.coef.name = "r",
                   p.accuracy = .001, r.accuracy = .01, col = "black")
plt_grp

# grouped scatterplot 
plt_grp <- ggplot(data = df, aes(x = t1, y = t2, col = group)) +
  geom_point(shape = 20, col = "black")+
  facet_wrap(. ~ group, nrow = 2) + 
  stat_smooth(formula = y ~ x, method = "lm", fullrange = T, se = T, alpha=0.1, fill = "black") +
  scale_color_manual(values = c(blue, red)) +
  theme + 
  theme(legend.position = "none") +
  xlab("Baseline assessment") + ylab("Outcome assessment") +
  ggpubr::stat_cor(method = "pearson", cor.coef.name = "r",
                   p.accuracy = .001, r.accuracy = .01, col = "black")
plt_grp

```


```{r, echo=F}
# grouped scatterplot 
plt_grp <- ggplot(data = df, aes(x = t1, y = t2, col = group)) +
  geom_point(shape = 20)+
  facet_wrap(. ~ group, nrow = 2) + 
  stat_smooth(formula = y ~ x, method = "lm", fullrange = T, se = T, alpha=0.1, fill = "black") +
  scale_color_manual(values = c(blue, red)) +
  theme + 
  theme(legend.position = "none") +
  xlab("Baseline assessment") + ylab("Outcome assessment") +
  ggpubr::stat_cor(method = "pearson", cor.coef.name = "r",
                   p.accuracy = .001, r.accuracy = .01, col = "black")
plt_grp


# grouped scatterplot 
plt_grp <- ggplot(data = df, aes(x = t1, y = t2, col = group)) +
  geom_point(shape = 20)+
  facet_wrap(. ~ group, nrow = 2) + 
  stat_smooth(formula = y ~ x, method = "lm", fullrange = T, se = T, alpha=0.1, fill = "black") +
  scale_color_manual(values = c(teal, orange)) +
  theme + 
  theme(legend.position = "none") +
  xlab("Baseline assessment") + ylab("Outcome assessment") +
  ggpubr::stat_cor(method = "pearson", cor.coef.name = "r",
                   p.accuracy = .001, r.accuracy = .01, col = "black")
plt_grp

# grouped scatterplot 
plt_grp <- ggplot(data = df, aes(x = t1, y = t2, col = group)) +
  geom_point(shape = 20)+
  facet_wrap(. ~ group, nrow = 2) + 
  stat_smooth(formula = y ~ x, method = "lm", fullrange = T, se = T, alpha=0.1, fill = "black") +
  scale_color_manual(values = c(cyan, coral)) +
  theme + 
  theme(legend.position = "none") +
  xlab("Baseline assessment") + ylab("Outcome assessment") +
  ggpubr::stat_cor(method = "pearson", cor.coef.name = "r",
                   p.accuracy = .001, r.accuracy = .01, col = "black")
plt_grp

# grouped scatterplot 
plt_grp <- ggplot(data = df, aes(x = t1, y = t2, col = group)) +
  geom_point(shape = 20)+
  facet_wrap(. ~ group, nrow = 2) + 
  stat_smooth(formula = y ~ x, method = "lm", fullrange = T, se = T, alpha=0.1, fill = "black") +
  scale_color_manual(values = c(purple, yellow)) +
  theme + 
  theme(legend.position = "none") +
  xlab("Baseline assessment") + ylab("Outcome assessment") +
  ggpubr::stat_cor(method = "pearson", cor.coef.name = "r",
                   p.accuracy = .001, r.accuracy = .01, col = "black")
plt_grp

```



## Line graphs

```{r, echo=F}


out <- summarySEwithin(data = df_long,
                       measurevar = "value",
                       betweenvars = "group",
                       withinvars = "timepoint")

# create plot
plt <- ggplot(data = out, aes(x = timepoint, y = value, col = group, group = group, shape = group, linetype = group)) +
  geom_errorbar(aes(ymin = value - ci, ymax = value + ci), width = .05, position = position_dodge(.2), col = "black", linetype = "solid") +
  geom_point(position = position_dodge(.2), size = 2) +
  geom_line(position = position_dodge(.2)) +
  scale_color_manual(values = c(blue, red)) +
  scale_shape_manual(values = c(16, 18)) +
  xlab("Experimental group") + ylab("Outcome assessment") +
  labs(caption = "Error bars represent 95%-CI.") +
  theme +
  theme(plot.caption = element_text(hjust=0))
plt

# create plot
plt <- ggplot(data = out, aes(x = timepoint, y = value, col = group, group = group, shape = group, linetype = group)) +
  geom_errorbar(aes(ymin = value - ci, ymax = value + ci), width = .05, position = position_dodge(.2), col = "black", linetype = "solid") +
  geom_point(position = position_dodge(.2), size = 2) +
  geom_line(position = position_dodge(.2)) +
  scale_color_manual(values = c(teal, orange)) +
  scale_shape_manual(values = c(16, 18)) +
  xlab("Experimental group") + ylab("Outcome assessment") +
  labs(caption = "Error bars represent 95%-CI.") +
  theme +
  theme(plot.caption = element_text(hjust=0))
plt

# create plot
plt <- ggplot(data = out, aes(x = timepoint, y = value, col = group, group = group, shape = group, linetype = group)) +
  geom_errorbar(aes(ymin = value - ci, ymax = value + ci), width = .05, position = position_dodge(.2), col = "black", linetype = "solid") +
  geom_point(position = position_dodge(.2), size = 2) +
  geom_line(position = position_dodge(.2)) +
  scale_color_manual(values = c(cyan, coral)) +
  scale_shape_manual(values = c(16, 18)) +
  xlab("Experimental group") + ylab("Outcome assessment") +
  labs(caption = "Error bars represent 95%-CI.") +
  theme +
  theme(plot.caption = element_text(hjust=0))
plt


# create plot
plt <- ggplot(data = out, aes(x = timepoint, y = value, col = group, group = group, shape = group, linetype = group)) +
  geom_errorbar(aes(ymin = value - ci, ymax = value + ci), width = .05, position = position_dodge(.2), col = "black", linetype = "solid") +
  geom_point(position = position_dodge(.2), size = 2) +
  geom_line(position = position_dodge(.2)) +
  scale_color_manual(values = c(purple, yellow)) +
  scale_shape_manual(values = c(16, 18)) +
  xlab("Experimental group") + ylab("Outcome assessment") +
  labs(caption = "Error bars represent 95%-CI.") +
  theme +
  theme(plot.caption = element_text(hjust=0))
plt


```

## Bar graphs

```{r, echo = F}
dir <- getwd()
code_dir <- gsub("/r_graphs", "", dir)

teach <- read.csv(file.path(code_dir, "Global_Teaching_Insights", "data_raw", "GTI-Teacher-Data.csv"))

# select relevant variables and save in a df
tmp <- teach[, grep("T_ID|COUNTRY|OTL_TL", names(teach))]

# compute descriptives for each country
out <- apply(tmp[, c(-1, -2)], MARGIN = 2, function(x) psych::describeBy(x, group = tmp$COUNTRY, mat=TRUE))

# transform out (list of data.frames) into df
out <- Reduce(dplyr::full_join,out)
out$item <- rep(names(tmp)[c(-1, -2)], each = length(unique(tmp$COUNTRY)))
out$vars <- NULL
out[, c(-1, -2)] <- round(out[, c(-1, -2)], 3)

# print in markdown
plt <- ggplot(data = out, aes(x = group1, y = mean, fill = group1)) +
  geom_bar(stat = "identity", width = 0.5) + 
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width=.1) +
  theme + 
  scale_fill_manual(values = ambition_palette) + guides(fill=FALSE) +
  facet_wrap(vars(item), ncol = 1) +
  xlab("Country") + ylab("Average OTL (based on teacher log)") +
  labs(caption = "Error bars represent SE.") + theme(plot.caption = element_text(hjust=0)) +
  ggtitle("OTL (source: teacher log) seperately for each country")

plt



```

## Font Sizes
```{r}

out <- summarySEwithin(data = df_long,
                       measurevar = "value",
                       betweenvars = "group",
                       withinvars = "timepoint")


# create plot
plt <- ggplot(data = out, aes(x = timepoint, y = value, col = group, group = group, shape = group, linetype = group)) +
  geom_errorbar(aes(ymin = value - ci, ymax = value + ci), width = .05, position = position_dodge(.2), col = "black", linetype = "solid") +
  geom_point(position = position_dodge(.2), size = 2) +
  geom_line(position = position_dodge(.2)) +
  scale_color_manual(values = c(blue, red)) +
  scale_shape_manual(values = c(16, 18)) +
  xlab("Timepoint") + ylab("Outcome assessment") +
  labs(caption = "Error bars represent 95%-CI.") +
  theme_bw(base_size = 14) + theme(legend.position = "bottom",
                                   text=element_text(family="Segoe UI")) +
  theme(plot.caption = element_text(hjust=0))
plt

# create plot
plt <- ggplot(data = out, aes(x = timepoint, y = value, col = group, group = group, shape = group, linetype = group)) +
  geom_errorbar(aes(ymin = value - ci, ymax = value + ci), width = .05, position = position_dodge(.2), col = "black", linetype = "solid") +
  geom_point(position = position_dodge(.2), size = 2) +
  geom_line(position = position_dodge(.2)) +
  scale_color_manual(values = c(blue, red)) +
  scale_shape_manual(values = c(16, 18)) +
  xlab("Timepoint") + ylab("Outcome assessment") +
  labs(caption = "Error bars represent 95%-CI.") +
  theme_bw(base_size = 11) + theme(legend.position = "bottom",
                                   text=element_text(family="Segoe UI")) +
  theme(plot.caption = element_text(hjust=0))
plt

# define theme for plot
theme <- theme_bw() + theme(
  text=element_text(family="Segoe UI"),
  plot.title = element_text(size=18, face="bold"),
  axis.title = element_text(size=14, face="bold"),
  axis.text = element_text(size=11),
  legend.title = element_text(size=14, face="bold"),
  legend.text = element_text(size=11),
  plot.caption = element_text(size=11),
  #legend.title = element_blank(),
  legend.position = "bottom"
)

# create plot
plt14 <- ggplot(data = out, aes(x = timepoint, y = value, col = group, group = group, shape = group, linetype = group)) +
  geom_errorbar(aes(ymin = value - ci, ymax = value + ci), width = .05, position = position_dodge(.2), col = "black", linetype = "solid") +
  geom_point(position = position_dodge(.2), size = 2) +
  geom_line(position = position_dodge(.2)) +
  scale_color_manual(values = c(blue, red)) +
  scale_shape_manual(values = c(16, 18)) +
  xlab("Timepoint") + ylab("Outcome assessment") +
  labs(caption = "Error bars represent 95%-CI.") +
  theme +
  theme(plot.caption = element_text(hjust=0))
plt14

# define theme for plot
theme <- theme_bw() + theme(
  text=element_text(family="Segoe UI"),
  plot.title = element_text(size=18, face="bold"),
  axis.title = element_text(size=13, face="bold"),
  axis.text = element_text(size=11),
  legend.title = element_text(size=13, face="bold"),
  legend.text = element_text(size=11),
  plot.caption = element_text(size=11),
  #legend.title = element_blank(),
  legend.position = "bottom"
)

# create plot
plt13 <- ggplot(data = out, aes(x = timepoint, y = value, col = group, group = group, shape = group, linetype = group)) +
  geom_errorbar(aes(ymin = value - ci, ymax = value + ci), width = .05, position = position_dodge(.2), col = "black", linetype = "solid") +
  geom_point(position = position_dodge(.2), size = 2) +
  geom_line(position = position_dodge(.2)) +
  scale_color_manual(values = c(blue, red)) +
  scale_shape_manual(values = c(16, 18)) +
  xlab("Timepoint") + ylab("Outcome assessment") +
  labs(caption = "Error bars represent 95%-CI.") +
  theme +
  theme(plot.caption = element_text(hjust=0))
plt13

# define theme for plot
theme <- theme_bw() + theme(
  text=element_text(family="Segoe UI"),
  plot.title = element_text(size=18, face="bold"),
  axis.title = element_text(size=12, face="bold"),
  axis.text = element_text(size=11),
  legend.title = element_text(size=12, face="bold"),
  legend.text = element_text(size=11),
  plot.caption = element_text(size=11),
  #legend.title = element_blank(),
  legend.position = "bottom"
)

# create plot
plt12 <- ggplot(data = out, aes(x = timepoint, y = value, col = group, group = group, shape = group, linetype = group)) +
  geom_errorbar(aes(ymin = value - ci, ymax = value + ci), width = .05, position = position_dodge(.2), col = "black", linetype = "solid") +
  geom_point(position = position_dodge(.2), size = 2) +
  geom_line(position = position_dodge(.2)) +
  scale_color_manual(values = c(blue, red)) +
  scale_shape_manual(values = c(16, 18)) +
  xlab("Timepoint") + ylab("Outcome assessment") +
  labs(caption = "Error bars represent 95%-CI.") +
  theme +
  theme(plot.caption = element_text(hjust=0))
plt12

# define theme for plot
theme <- theme_bw() + theme(
  text=element_text(family="Segoe UI"),
  plot.title = element_text(size=18, face="bold"),
  axis.title = element_text(size=11, face="bold"),
  axis.text = element_text(size=11),
  legend.title = element_text(size=11, face="bold"),
  legend.text = element_text(size=11),
  plot.caption = element_text(size=11),
  #legend.title = element_blank(),
  legend.position = "bottom"
)

# create plot
plt11 <- ggplot(data = out, aes(x = timepoint, y = value, col = group, group = group, shape = group, linetype = group)) +
  geom_errorbar(aes(ymin = value - ci, ymax = value + ci), width = .05, position = position_dodge(.2), col = "black", linetype = "solid") +
  geom_point(position = position_dodge(.2), size = 2) +
  geom_line(position = position_dodge(.2)) +
  scale_color_manual(values = c(blue, red)) +
  scale_shape_manual(values = c(16, 18)) +
  xlab("Timepoint") + ylab("Outcome assessment") +
  labs(caption = "Error bars represent 95%-CI.") +
  theme +
  theme(plot.caption = element_text(hjust=0))
plt11

```

